plugins {
    id 'com.android.library'
}
apply from: rootProject.file('gradle/maven-publish.gradle')

android {
    compileSdkVersion config['compile-sdk']
    buildToolsVersion config['build-tools']

    defaultConfig {
        minSdkVersion config['min-sdk']
        targetSdkVersion config['target-sdk']
        versionCode 1
        versionName version
    }
}

dependencies {
    deps.with {
        implementation it['x-annotations']
        api it['commonmark']

        // @since 4.1.0 to allow PrecomputedTextSetterCompat
        // note that this dependency must be added on a client side explicitly
        compileOnly it['x-core']
        compileOnly it['x-appcompat']
    }
}
